# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = W6_PrgAssign_NestLoop_EggsQ4.o
LINKOBJ  = W6_PrgAssign_NestLoop_EggsQ4.o
LIBS     = -L"C:/Users/Mariya/Dev-Cpp/MinGW64/lib" -L"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Mariya/Dev-Cpp/MinGW64/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Mariya/Dev-Cpp/MinGW64/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = W6_PrgAssign_NestLoop_EggsQ4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

W6_PrgAssign_NestLoop_EggsQ4.o: W6_PrgAssign_NestLoop_EggsQ4.cpp
	$(CPP) -c W6_PrgAssign_NestLoop_EggsQ4.cpp -o W6_PrgAssign_NestLoop_EggsQ4.o $(CXXFLAGS)
