# Project: rectangleClass
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = rectangle.o rectangle_test.o
LINKOBJ  = rectangle.o rectangle_test.o
LIBS     = -L"C:/Users/Mariya/Dev-Cpp/MinGW64/lib" -L"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Mariya/Dev-Cpp/MinGW64/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Mariya/Dev-Cpp/MinGW64/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = rectangleClass.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

rectangle.o: rectangle.cpp
	$(CPP) -c rectangle.cpp -o rectangle.o $(CXXFLAGS)

rectangle_test.o: rectangle_test.cpp
	$(CPP) -c rectangle_test.cpp -o rectangle_test.o $(CXXFLAGS)
