# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = W14_PrgAssignP2_Q2_Eggensperger.o
LINKOBJ  = W14_PrgAssignP2_Q2_Eggensperger.o
LIBS     = -L"C:/Users/Mariya/Dev-Cpp/MinGW64/lib" -L"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Mariya/Dev-Cpp/MinGW64/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Mariya/Dev-Cpp/MinGW64/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Mariya/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = W14_PrgAssignP2_Q2_Eggensperger.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

W14_PrgAssignP2_Q2_Eggensperger.o: W14_PrgAssignP2_Q2_Eggensperger.cpp
	$(CPP) -c W14_PrgAssignP2_Q2_Eggensperger.cpp -o W14_PrgAssignP2_Q2_Eggensperger.o $(CXXFLAGS)
